### PR TITLE
Fix checksum for python-vispy-0.12.2.tar.gz

### PR DESCRIPTION
**Pull request by jonpatterns**

### CODE REVIEW

**Comment by acxz** [comment]
Thx for the PR! do you mind updating the .SRCINFO file via `makepkg --printsrcinfo > .SRCINFO` as well. that is required to update the package on the AUR.

**Comment by jonpatterns** [comment]
Will do, but will have to be tomorrow.

**Comment by jonpatterns** [comment]
close to make new pull request from fork including scrinfo change

**Comment by acxz** [comment]
just as a pointer for the future,you can overwrite your existing commit, with `git commit --amend` and then a `git push origin master -f` so you don't have to make a new PR every time you want a different commit.

**Pull request closed without merging**
