### PR TITLE
[pagmo-git] Build with IPO

### PR DESCRIPTION
**Pull request by ow97**
Build with IPO (aka LTO) as per https://github.com/esa/pagmo2/pull/413

### CODE REVIEW

**Comment by acxz** [comment]
Sweet thanks for the PR! However, I am afraid the PKGBUILD is not up to spec. Please be sure to read: https://wiki.archlinux.org/index.php/PKGBUILD

The .SRCINFO has to be changed for it to be reflected on the AUR, and thus the pkgver has to be increated. If the commit is the same then the pkgrel variable must be bumped up.

Also if you could add the latest changes from the pagmo package that would be great as well. The `cmake_options` field is removed in the latest pagmo PKGBUILD but this change has not been propagated to this PKGBUILD yet.

**Comment by acxz** [comment]
Since the pkgver has changed the pkgrel should be bumped back down to 1 instead of 3.

**Comment by acxz** [comment]
Sweet, I still would like for you to incorporate the changes from the `pagmo` package to the `pagmo-git` packages, before I merge this in. Let me know if you want me to take care of that.

**Comment by ow97** [comment]
This is my first PKGBUILD contribution. The patience you have shown and help you've provided is greatly appreciated. Thank you.

> Also if you could add the latest changes from the pagmo package that would be great as well. The cmake_options field is removed in the latest pagmo PKGBUILD but this change has not been propagated to this PKGBUILD yet.
Happy to give this a go, but given that I'd probably need some hand holding I'm also perfectly happy for you to get it done in 1/10th of the time :)

**Comment by acxz** [comment]
No problemo, I was like that just a year ago lol. As with all things it takes experience but having someone help you out really makes a difference.

**Comment by acxz** [comment]
@ow97 I went ahead and updated the PKGBUILD, you can now add your patch. Note you will have to rebase from master. If you are not familar than I would just recommend deleting your current branch and starting again, remembering to update the pkgrel and .SRCINFO as needed.

**Comment by acxz** [comment]
Remeber that the .SRCINFO needs to be updated. Since the pkgver is the same, we need to update the pkgrel from 1 to 2 this time.

**Comment by acxz** [comment]
An easy way to generate the .SRCINFO is to use the `makepkg --printsrcinfo` command
See: the Generating section under: https://wiki.archlinux.org/index.php/.SRCINFO

There is no need to manually write to the .SRCINFO, you should write to the PKGBUILD file and then create the .SRCINFO from the command automatically. This ensures that both files are synced up. For example in this case the pkgrel is updated on the .SRCINFO but not the PKGBUILD, which is not good.

**Comment by ow97** [comment]
You have the patience of a saint :)

**Comment by acxz** [comment]
Just tested it and looks good. LGTM!
Thx for your contribution.

**Comment by acxz** [comment]
Pushed to the AUR

**Pull request merged**
