### PR TITLE
libdart 6.10.1

### PR DESCRIPTION
**Pull request by AchmadFathoni**

### CODE REVIEW

**Comment by acxz** [comment]
Hey @AchmadFathoni the semester is over and I'm back! I'll try to close all the loose ends so far by the end of today.

**Review by acxz — APPROVED** [review]

**Comment by acxz** [comment]
looks like I dont own this package anymore

**Comment by AchmadFathoni** [comment]
Do you want to be co-maintainer? that would be an honor.

**Comment by acxz** [comment]
Eh its fine. I dont work on dart too extensively at the moment. It's better if someone more active takes up the role. I do suggest if possible for your packages that you have inherited you set up a repo like this one. Just so that in the future it makes contributions much easier.

**Comment by acxz** [comment]
@AchmadFathoni  actually thinking about it, maybe having me as co-maintainer is nice, so that you don't have to create a repo like this one and we can just use this one. If others want to patch/update they can easily send PRs here and can merge them in.

**Comment by AchmadFathoni** [comment]
Ok. Would you mind to orphan this packages:
```
ros-noetic-controller-manager-msgs
ros-noetic-rqt-srv
ros-noetic-rqt-reconfigure
ros-noetic-rospy
ros-noetic-roscpp
ros-noetic-gazebo-ros-pkgs
ros-noetic-gazebo-ros-control
ros-noetic-gazebo-ros
ros-noetic-gazebo-plugins
ros-noetic-gazebo-dev
ros-noetic-gazebo-msgs
ros-noetic-gazebo-dev

```
I need to update them.

**Comment by acxz** [comment]
Seems like you are already a maintainer for those packages. Sorry for not being punctual on that.

**Pull request merged**
