### PR TITLE
[ignition-math] Added patch for header bug

### PR DESCRIPTION
**Pull request by Ramdambo**

### CODE REVIEW

**Comment by acxz** [comment]
Thx for the PR, @Ramdambo, but it would be nice if we can take the patch directly upstream so that it is verified and that we don't increase the code burden we have to deal with. Also be sure to fix the conflicts and base your work off the latest commits.

**Comment by Ramdambo** [comment]
What do you mean by "taking the patch directly upstream" ? 
Sorry, I'm pretty new to this stuff.

**Comment by acxz** [comment]
No worries, :) Take a look at the reference I linked in the comment [here](https://github.com/acxz/pkgbuilds/issues/27#issuecomment-631591641). See how instead of copy and pasting the patch and having the patch in this local repo/folder, we 'pull' in the patch from the internet directly from the github commit.

**Comment by acxz** [comment]
Sweet thx for iterating. Also one more thing: don't forget to bump pkgrel when updating the PKGBUILD.

**Comment by Ramdambo** [comment]
Sure, no thing, thanks for your guidance !

It should be on 4 right ? 
Or did I miss something ?

**Comment by acxz** [comment]
On 5, always one up from the last commit. Since the last one was 4 (due to changing the source url) this one will be 5.

**Comment by Ramdambo** [comment]
Oh okay, I see! Thanks for clarifying!

**Comment by acxz** [comment]
LGTM! Hope you learned some useful things!

**Pull request merged**
