### PR TITLE
[ignition-tools] Fix checksum and source directory

### PR DESCRIPTION
**Pull request by alexdewar**
Currently the checksum check fails and the directory into which the
PKGBUILD tries to cd doesn't exist.

### CODE REVIEW

**Review by acxz — CHANGES_REQUESTED** [review]
thx for the PR @alexdewar can you also update the redirected links?

See: https://github.com/acxz/pkgbuilds/commit/e43481f5c15d8e7bd2fc1e42a075bf355bd4c67e
as an example

**Comment by alexdewar** [comment]
Done

**Comment by alexdewar** [comment]
> btw @alexdewar would you be interested in helping maintain a `gazebo-arch` repo that hosts all gazebo related PKGBUILDs? This would include the current ignition-* packages (which might soon be renamed due to upstream decisions) and the gazebo package. Have a centralized place will make maintaining easier as currently they are split b/t me, @AchmadFathoni, @homalozoa, and you

Totally. I'm currently trying to fix up the gazebo package and I've been running into build errors with various ignition packages, so I think it's a great idea.

**Comment by acxz** [comment]
Sweet, I'll make a github org called gazebo-arch and send you an invitation later today

**Comment by alexdewar** [comment]
Great :-)

**Comment by acxz** [comment]
Sent invite, decided to go with just a repo for rn using [aurpublish](https://github.com/elischwartz/aurpublish)

**Comment by acxz** [comment]
Take a look at how the ROCm community on Arch uses it: https://github.com/rocm-arch/rocm-arch for an example on how I would like to model the gazebo-arch repo

**Pull request merged**
