### PR TITLE
sdformat: amend urdfdom as dependency

### LINKED ISSUE #51: [sdformat] fatal error: urdf_model/model.h: No such file or directory
while building `sdformat` I get the following error:
```
[ 52%] Building CXX object src/CMakeFiles/sdformat9.dir/Types.cc.o
/home/arch/.cache/pikaur/build/sdformat/src/sdformat-sdformat9_9.2.0/src/parser_urdf.cc:30:10: fatal error: urdf_model/model.h: No such file or directory
   30 | #include <urdf_model/model.h>
      |          ^~~~~~~~~~~~~~~~~~~~
```
I have `urdf_model/model.h` already installed in `/opt/ros2/`. Do I have to point there?

### PR DESCRIPTION
**Pull request by goekce**
fixes #51

### CODE REVIEW

**Comment by acxz** [comment]
Also one more think that I want to point out: notice how next to your commit you don't have the same avatar as your github user? That is because your commit email is not associated with your github account. I recommend you add that email as well to your github account under settings. You can associate more than one email to your github account.

**Comment by goekce** [comment]
Thank you for reaching your hand on my first pull request @acxz !

**Comment by acxz** [comment]
no problemo!

**Comment by acxz** [comment]
LGTM!

**Comment by goekce** [comment]
@acxz thank you, I added my mail to Github :+1: 

 Can you please edit my mail address out from your post to avoid potential spam?

**Comment by acxz** [comment]
If you do care about spam, you should hide your email on your commit messages. See: your email settings page and check the keep email address private and block command line pushes that expose my message.

Editing the comment still keeps the email in the post, since each version of comments are also saved. And the commit will always have the email.

Just some more tips.

**Pull request merged**
