### PR TITLE
[xrotor] fix 'Rank mismatch' error during compilation

### PR DESCRIPTION
**Pull request by mx212**
* add -fallow-argument-mismatch compile flag to PKGBUILD

### CODE REVIEW

**Review by acxz — CHANGES_REQUESTED** [review]
Sweet, thanks for the PR!

Just a couple things since we will be pushing this directly to the AUR. Can you bump the pkgrel and update the .SRCINFO file?

https://wiki.archlinux.org/title/PKGBUILD#pkgrel
https://wiki.archlinux.org/title/.SRCINFO

**Comment by mx212** [comment]
Thank you for walking me through things!
I forgot about the .SCRINFO file. I added a new commit to bump the pkgrel number.

**Comment by acxz** [comment]
no worries!
the pkgrel should be bumped in the PKGBUILD and then `makepkg --printscrinfo > .SRCINFO` should be ran to automatically update the .SRCINFO file.

**Comment by mx212** [comment]
Should have read both wiki articels.. I fixed that.

**Review by acxz — APPROVED** [review]
thx for iterating @mx212 !

**Pull request merged**
