### PR TITLE
Add support for c++11 std to fix build error.

### LINKED ISSUE #133: [cegui] Build error on version 0.8.7
Build fails. It requires compiler and library support for ISO C++ 2011 standard. Requires -std=c++11 or -std=gnu++11 compiler option.
image

### PR DESCRIPTION
**Pull request by navti**
Closes #133 

Added support for c++11 definitions. Fixes build error on cegui 0.8.7.

### CODE REVIEW

**Review by acxz — CHANGES_REQUESTED** [review]
Sorry for the late response,

Looks good but need two more changes.
Can you bump up the pkgver number in the PKGBUILD file and run
`makepkg --printsrcinfo > .SRCINFO` to regenerate the `.SRCINFO` file and add that with the commit.

See https://wiki.archlinux.org/title/Creating_packages#pkgver()
and https://wiki.archlinux.org/title/.SRCINFO

**Comment by navti** [comment]
Hey. I've made the changes as you requested. Please do review and merge. Thanks!

**Review by acxz — CHANGES_REQUESTED** [review]
Ah I totally apologize, I meant pkgrel instead of pkgver. pkgver is the upstream package version, pkgrel (package relative) is the relative version for our specific arch package.

Could you do that little fix? Sorry about that.

**Comment by navti** [comment]
Hi. Sorry about that. It's fixed now.

**Review by acxz — APPROVED** [review]

**Pull request merged**
