### PR TITLE
python-dm-tree: use system abseil-cpp + correctness fixes

### LINKED ISSUE #245: [python-dm-tree] fails to build
This is the output of `makepkg -i` on AUR target python-dm-tree: https://pastebin.com/NUpMyc3t

I get similar results with target python-dm-tree-git. The strange thing is that this package seems to be trying to download and build abseil-cpp, which is available as a separate AUR package (abseil-cpp-git) and had no build issues when I installed it separately.

Is there an upstream issue, or does there seem to be something hinky with my system configuration?

### PR DESCRIPTION
**Pull request by intelfx**
Fixes #245.

### CODE REVIEW

**Comment by moghingold** [comment]
When I try to manually update the files using this PR I get this output:

```
==> Validating source files with sha256sums...
    python-dm-tree-0.1.8.tar.gz ... Passed
    CMakeLists.txt.patch ... FAILED
==> ERROR: One or more files did not pass the validity check!
```

Looks like a validity check needs to be added for CMakeLists.txt.patch

Also, please consider making this changes for python-dm-tree-git as well, since it is also affected by #245 .

**Comment by matiasvlevi** [comment]
I updated the patch with intelfx/acxz-pkgbuilds#1

`python-dm-tree` is now installed on my system

**Comment by intelfx** [comment]
@moghingold yep, fixed

**Comment by acxz** [comment]
@intelfx thx for the fix! LGTM!

**Pull request merged**
