### PR TITLE
Declare assignment operator private for SIP

### PR DESCRIPTION
**Pull request by hadogenes**
Patch based on 
https://github.com/orocos/orocos_kinematics_dynamics/issues/260 for v1.4.0

### CODE REVIEW

**Comment by hadogenes** [comment]
It only builds now, but I didn't test if it works

**Comment by acxz** [comment]
o.O so fast haha, let's make sure it builds ;)

**Comment by acxz** [comment]
Also if possible let's use the patch committed upstream directly instead of maintaining our own version. See: https://github.com/acxz/pkgbuilds/blob/master/ignition-math/PKGBUILD#L17

**Comment by hadogenes** [comment]
I had this patch for a while now.
I've send it to previous maintainer, but without answer.

**Comment by acxz** [comment]
Sure but let's try to use the upstream version. I don't like hardcoding patches if possible.

**Comment by hadogenes** [comment]
I tried, but this version (1.4.0) has slightly different sources then _master_

**Comment by acxz** [comment]
ahh rip kk well lets get this merged! thx for being on top of this!

**Comment by acxz** [comment]
rip i did it too early, the .SRCINFO....

**Comment by hadogenes** [comment]
could you set the .SRCINFO and version update, please

**Comment by acxz** [comment]
in favor of ease, I did a force push instead of blowing up the folder and redoing the commit. should be fine now. Just keep in mind next to always have a .SRCINFO with a PKGBUILD change. I guess it was too early in the morning for me to notice it during my review lol.

**Comment by hadogenes** [comment]
I think we should set version to 1.4.0**-2**

**Comment by acxz** [comment]
:+1:

**Pull request merged**
