### PR TITLE
Update PKGBUILD

### PR DESCRIPTION
**Pull request by DRM-Free**
Conflicts must not be empty

### CODE REVIEW

**Comment by acxz** [comment]
Hey @DRM-Free thx for the PR! However, sadly your PR is not up to spec.
Please see: https://wiki.archlinux.org/index.php/PKGBUILD
Hint: take a look at `pkgrel`

**Comment by acxz** [comment]
Thx for fix however, there is still one more thing: `.SRCINFO`.
https://wiki.archlinux.org/index.php/.SRCINFO

**Comment by DRM-Free** [comment]
Sorry for the mistakes, I am still learning. Thank you for the help.

**Comment by acxz** [comment]
No problemo, we were all like that at some point.
Looks good thx for the contribution!

**Pull request merged**
